---
- name: Challanges Accpted
  hosts: testserver
  remote_user: root
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: installed
    - name: Create html FIle
      shell: echo "Hello Prasad from Ansible" > /var/www/html/index.html
      args:
        excutable: /bin/bash
      notify:
        - Reload Apache
    - name: Public IP
      shell:
        cmd: curl http://169.254.169.254/latest/meta-data/public-ipv4
        register: curl
    - debug: var=curl.stdout_lines
  handlers:
    - name: Reload Apache
      service:
         name: httd
         state: reloaded         
